name: Deploy AKS Cluster

on:
    workflow_dispatch:
        inputs:
            cluster_name:
                description: 'Name of the AKS Cluster'
                required: true
                default: 'my-aks'
            resource_group:
                description: 'Resource Group for the AKS Cluster'
                required: true
                default: 'XResourse-JP-1'

permissions:
  id-token: write
  contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                fetch-depth: 0

            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              working-directory: ./terraform/aks
              run: terraform init

            - name: Terraform Plan
              working-directory: ./terraform/aks
              run: terraform plan \
                -var="prefix=${{ inputs.cluster_name }}" \
                -var="rg=${{ inputs.resource_group }}"

            - name: Terraform Apply
              working-directory: ./terraform/aks
              run: terraform apply -auto-approve \
                -var="prefix=${{ inputs.cluster_name }}" \
                -var="rg=${{ inputs.resource_group }}"
             
    configure:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
            
            - name: Install kubectl
              uses: azure/setup-kubectl@v4

            - name: Get AKS credentials
              run: |
                az aks get-credentials \
                --resource-group ${{inputs.resource_group}} \
                --name ${{inputs.cluster_name}} \
                --overwrite-existing

            - name: Install Gateway API Fabric
              run: |
                kubectl kustomize "https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.2.1" | kubectl apply -f -

            - name: Install Helm
              uses: azure/setup-helm@v4.3.0

            - name: Install your application
              run: |
                helm install ngf oci://ghcr.io/nginx/charts/nginx-gateway-fabric --create-namespace -n nginx-gateway
